DROP TABLE department;

CREATE TABLE department(
	dept_id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
	dept_id_external VARCHAR(5) NOT NULL UNIQUE, 
	dept_name VARCHAR(50) NOT NULL
);
--CALL SYSPROC.ADMIN_CMD( 'REORG TABLE "economia".DEPARTMENT' );
ALTER TABLE department ADD CONSTRAINT PK_dept_id PRIMARY KEY(dept_id);

--CREATE SEQUENCE SEQ_dept_id START WITH 1 INCREMENT BY 1;
-- ALTER SEQUENCE SEQ_dept_id RESTART WITH 1

